Skipping because of a known bug with Arc.intersect(Arc).

https://github.com/mathandy/svgpathtools/issues/43

intersecting
    this Arc(start=(-12.609819852+48.7827211639j), radius=(55.4+55.4j), rotation=0.0, large_arc=False, sweep=True, end=(-8.24106947161+64.3408209792j))
    next Arc(start=(-8.24115581208+64.3401469105j), radius=(55.4+55.4j), rotation=0.0, large_arc=False, sweep=True, end=(-24.348596757+110.880509115j))
Traceback (most recent call last):
  File "/home/seb/gcoder/test/../svg2gcode", line 69, in <module>
    new_paths = gcoder.offset_path(input_path, offset)
  File "/home/seb/gcoder/gcoder.py", line 487, in offset_path
    intersections = this_seg.intersect(next_seg)
  File "/home/seb/gcoder/svgpathtools/svgpathtools/path.py", line 1790, in intersect
    tol=tol, tol_deC=tol)
  File "/home/seb/gcoder/svgpathtools/svgpathtools/bezier.py", line 302, in bezier_intersections
    bbox1 = bezier_bounding_box(pair.bez1)
  File "/home/seb/gcoder/svgpathtools/svgpathtools/bezier.py", line 210, in bezier_bounding_box
    if len(bez) == 4:
TypeError: object of type 'Arc' has no len()

